---
# This playbook can set up:
# - A Jenkins coordinator node, though most of the Jenkins configuration is still manual.
# - A Jenkins worker node, though most of the Jenkins configuration is still manual.
# - A hibernate.org/in.relation.to website node.

- hosts: awscislaves
  remote_user: fedora
  become: yes

  roles:
    - common
    - aws
    - jenkins-common
    - jenkins-slave
    - awsslave


- hosts: cimaster
  remote_user: ec2-user
  become: yes

  roles:
    - common
    - aws
    - jenkins-common
    - jenkins-master

- hosts: websites
  remote_user: ec2-user
  become: yes

  roles:
    - common
    - aws
    - websites
